### ISSUE TITLE
test fails, but no indication why

### ISSUE THREAD

**Issue by tari3x** [netheril96/securefs#135]
One of the tests failed during build as shown below. It would be nice to know why it failed and whether it is still ok to use securefs on this system.

```
Test project /dev/shm/securefs-build-JoREJ
    Start 1: sec_test
1/4 Test #1: sec_test .........................   Passed    1.36 sec
    Start 2: simple_test
2/4 Test #2: simple_test ......................***Failed   38.60 sec
    Start 3: cryptest
3/4 Test #3: cryptest .........................   Passed    5.75 sec
    Start 4: argon2_test
4/4 Test #4: argon2_test ......................   Passed   12.73 sec

75% tests passed, 1 tests failed out of 4

Total Test time (real) =  58.45 sec

The following tests FAILED:
          2 - simple_test (Failed)
Errors while running CTest
++ realpath ./securefs
+ SECUREFS_BINARY_PATH=/dev/shm/securefs-build-JoREJ/securefs
+ echo 'Please copy /dev/shm/securefs-build-JoREJ/securefs to anywhere in your $PATH to use it'
Please copy /dev/shm/securefs-build-JoREJ/securefs to anywhere in your $PATH to use it
```

**Comment by netheril96** [comment]
Hmm, can you cd into the build directory and find any logs?

**Comment by tari3x** [comment]
I see a bunch of these, perhaps related?

```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/avatar/tynology/build/securefs/test/simple_test.py", line 764, in randomly_act_on_file
    run_once(f)
  File "/home/avatar/tynology/build/securefs/test/simple_test.py", line 751, in run_once
    f.write(random.randbytes(rng.randrange(1, 5000)))
AttributeError: module 'random' has no attribute 'randbytes'
```

**Comment by netheril96** [comment]
Please try building at HEAD again.

**Comment by tari3x** [comment]
Works! Thanks a lot for the quick fix!
