### ISSUE TITLE
followed build instructions, still getting "--vcpkg_root must point to a directory."

### ISSUE THREAD

**Issue by tari3x** [netheril96/securefs#160]
This is possibly just a matter of documenting some additional steps. I installed vcpkg as per instructions, but I'm still getting the below. How does the build of securefs figure out where vcpkg lives?

```
$ python3 build.py --enable_test 
Traceback (most recent call last):
  File "build.py", line 99, in <module>
    main()
  File "build.py", line 64, in main
    "--vcpkg_root must point to a directory. Install from https://vcpkg.io if necessary."
ValueError: --vcpkg_root must point to a directory. Install from https://vcpkg.io if necessary.
exit 1
```

As a meta point, is introducing a new unusual moving part into the build really worth it? Every other project seems to work just fine without vcpkg.

**Comment by tari3x** [comment]
Ah, figured it out:
```
python3 build.py --enable_test --vcpkg_root=/home/avatar/bin/vcpkg/
```

I guess just having vcpkg in the path is not enough?

**Comment by netheril96** [comment]
> I guess just having vcpkg in the path is not enough?

Thanks for the suggestion. I just pushed commit 14b0b83 to look up in the path.

> As a meta point, is introducing a new unusual moving part into the build really worth it?

I'm tired to maintaining the dependencies of this project within the repository. Especially on each upgrade of CMake, it is very tedious to make it work with CMake.

**Comment by netheril96** [comment]
Correction, the hardest dependency to upgrade is Crypto++ rather than CMake.
